 name: CI

 on:
   push:
     branches:
       - KAN-1-setup-github-actions

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Get Your Code
         uses: actions/checkout@v2

       - name: Say Hello to the World
         run: echo "Hello, World!"

       - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: patiltushar9820
          minimum-approvals: 1
          issue-title: "Deploying v1.0.0 to main"
          issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to main."
          exclude-workflow-initiator-as-approver: false

       - name: Run Python file
         run: python ./test.py